export ARCHS = armv7 arm64

include theos/makefiles/common.mk

BUNDLE_NAME = InfiniteHealth
InfiniteHealth_FILES = InfiniteHealth.mm
InfiniteHealth_INSTALL_PATH = /Library/MCLoader/
InfiniteHealth_FRAMEWORKS = UIKit
InfiniteHealth_PRIVATE_FRAMEWORKS = Preferences
InfiniteHealth_BUNDLE_EXTENSION = mcpemod
InfiniteHealth_LIBRARIES = MinecraftMod substrate

include $(THEOS_MAKE_PATH)/bundle.mk